import java.io.*;
class hc
{//class starts here
    String name; // to accept the player's name;
    String toss; // to accept player's choice of taking odd or even for toss;
    String dec; //to accept player's choice of batting or bowling first;
    int aa; // converting the random real number generated by 'rr' into a random whole number run for the computer;
    int ii; // used in for loops;
    int bb; // to accept the player's number;
    int tt; // to accept player's number during toss
    int flag;// used as a sign to send various messages to the main method ("figuratively");
    double rr; // to generate a random real number;
    int score1; // to store the latest runs scored by the player;
    int score2; // to store the latest runs scored by the computer;
    int target; // to store the target,i.e, the runs to be scored in the second innings to win
    int ball=0;//to count and display the number of balls
    int over;//to store the number of overs the player wants to play
    float strt;//to calculate and store the strike rate of both the player and the computer in the first innings of the match
    float strt2;//to calculate and store the strike rate of both the player and the computer in the second innings of the match
    int sum; //to store the sum of the numbers entered by user and of the computer during toss;
    int ff=0;//to show a message of Half Century only once when the player reaches a score of 50 runs;
    int cc=0;//to show a message of Century only once when the player reaches a score of 100 runs;
    int c; // used in for loops to create a specific design;
    InputStreamReader isr=new InputStreamReader(System.in);
    BufferedReader br=new BufferedReader(isr);

    String Welcome_Player()throws IOException   
    {//method Welcome_Player starts here
        System.out.println("=======================");
        System.out.println("| WELCOME TO THE GAME |");
        System.out.println("=======================");
        System.out.println();
        System.out.print("Enter Your Good Name : ");
        name=br.readLine();//Storing the name of player
        for(c=0;c<=2;c++)
        System.out.println("====================================");
        System.out.println("Hello "+name+",");
        System.out.println(".");
        System.out.println("WELCOME TO THE CRICKET-MANIA");
        System.out.println(".");
        return(name);// So that name can be printed in the Result method
    }//method Welcome_Player ends here

    void Instructions()throws IOException
    {//method Instructions starts here
        System.out.println("I N S T R U C T I O N S :");
        System.out.println(".");
        System.out.println("This Game Is Similar To The Hand-Cricket Game Played By Kids.");
        System.out.println(".");
        System.out.println("The Number Of Overs To Be Played Will Be Decided By The Player.");
        System.out.println(".");
        System.out.println("A Toss Will Be Held. The Player Will Have to Choose Between Odd & Even.");
        System.out.println(".");
        System.out.println("In The Toss, Player Will Have To Enter A Number Followed By A Number Entered By The Computer.");
        System.out.println(".");
        System.out.println("If The Sum Of Those Two Numbers Matches With The Decision Taken By The Player Earlier i.e Odd/Even, The Player Wins The Toss.");
        System.out.println(".");
        System.out.println("If The Toss Is Won By The Player, He/She Will Have To Choose Between Batting/Bowling.");
        System.out.println(".");
        System.out.println("If The Computer Wins The Toss, It Will Decide Between Batting/Bowling.");
        System.out.println(".");
        System.out.println("Only Numbers Between 1 & 6 (Both Inclusive) Will Be Accepted.");
        System.out.println(".");
        System.out.println("Enter The Numbers Carefully Without Making Any Mistake.");
        System.out.println(".");
        System.out.println("If The Number Entered By The Computer Is Same As The Number Entered By You,");
        System.out.println("The One Who is Batting Will Be Declared As Out.");
        System.out.println(".");
        System.out.println("Your Final Score Will Be The Sum Of The Numbers You Entered Before Getting Out.");
        System.out.println(".");
        System.out.println("In The Second Innings, You Will Have To Bowl If You Batted First And Vice-Versa.");
        System.out.println(".");
        System.out.println("While Bowling, Try To Enter A Number Similar To The Number Entered By The Computer.");
        System.out.println(".");
        System.out.println("The Game Will Automatically Stop If The Number Of Overs You Had Played Goes Beyond The Number Of Overs You Decided To Play Earlier");
        System.out.println(".");
        System.out.println("The One Who Scores More Runs In The Game, Finally Wins!!");
        System.out.println(".");
        for(c=0;c<=2;c++)
            System.out.println("====================================");
    }//method Instructions ends here

    int Over()throws IOException
    {//method Over starts here
        System.out.println("How many overs would you like to play?");
        over=Integer.parseInt(br.readLine());
        if(over>10)//if the user chooses to play a game of more than 10 overs..
        {for(ii=1;ii>0;ii++)//will continuously run until the player enters an appropriate number of overs
            {System.out.println("Sorry..But You Cannot Play A Game Of More Than 10 Overs");
                System.out.println("How many overs would you like to play?");
                over=Integer.parseInt(br.readLine());
                if(over>10)
                    continue;
                else
                    break;
            }
        }
        return(over);//So that first and second innings run only till the limited overs entered by the player
    }//method Over ends here

    int Odd_or_Even()throws IOException
    {//method Odd_or_Even starts here
        System.out.println("What is Your Choice :-");
        System.out.println("1. Odd");
        System.out.println("2. Even");
        System.out.println();
        toss=br.readLine();
        if(toss.charAt(0)=='1'||toss.equals("1.")||toss.equalsIgnoreCase("odd"))
        flag=1;//if player chooses "Odd" it sends 1 as a signal to main method
        if(toss.charAt(0)=='2'||toss.equals("2.")||toss.equalsIgnoreCase("even")||toss.equalsIgnoreCase("eve"))
        flag=2;//if player chooses "Even" it sends 2 as a signal to main method
        return flag;
    }//method Odd_or_Even ends here
    
    int Toss(int n)throws IOException    
    {//method Toss starts here
        System.out.println("====================================");
        System.out.println("ITS TIME FOR THE \"TRICKY TOSS\" !!");
        System.out.println("====================================");
        System.out.println();
        System.out.println("Enter Your Number: ");
        tt=Integer.parseInt(br.readLine());//to store number entered by player during toss
        if(tt>6||tt<1)//checks whether player has entered an appropriate number (between 1 and 6)
        {for(ii=1;ii>0;ii++)//if number is an inappropriate number, it continuously runs until the player enters an appropriate number
            {System.out.println("YOU HAVE EITHER TRIED TO CHEAT OR ENTERED A WRONG INPUT..");
                System.out.println("YOU CANNOT ENTER A NUMBER ABOVE 6 OR BELOW 1.");
                System.out.println("PLEASE ENTER YOUR NUMBER AGAIN CAREFULLY :-");
                tt=Integer.parseInt(br.readLine());
                if(tt>6||tt<1)
                    continue;
                else
                    break;
            }
        }
        rr=((Math.random())*6);
        rr=rr+1;//so that a number between 1 & 6 gets printed, elsewise it prints a number between 0 & 6
        aa=(int)(rr);//stores the number to be printed by the computer
        System.out.println();
        System.out.println("Computer's Number: "+aa);
        System.out.println();
        System.out.println("**********");
        System.out.println();
        sum=tt+aa;//stores sum of the two numbers printed during toss
        /*Here 'n' is a number that is sent by the method "Odd_or_Even" by a variable "flag"
        *If the player chooses Odd it sends 1 which is an odd number
        *If the player chooses Even its sends 2 which is an even number
        */
        if(n%2!=0)//means if n is an Odd number,i.e. if it is 1,i.e if the player has chosen "Odd"...
        {if(sum%2!=0)//checks if sum of the two numbers during toss is also Odd
                return(1);//1 denotes that the player has won the Toss
            else
                return(0);//0 denotes that the player has lost the Toss
        }
        else//means if n is an Even number,i.e. if it is 2,i.e if the player has chosen "Even"...
        {if(sum%2==0)//checks if sum of the two numbers during toss is also Even
                return(1);//1 denotes that the player has won the Toss
            else
                return(0);//0 denotes that the player has lost the Toss
        }
    }//method Toss ends here

    int Won_The_Toss()throws IOException
    {//method Won_The_Toss starts here
        System.out.println();
        System.out.println("========================================");
        System.out.println("Congratulations!!! You Have Won The Toss");
        System.out.println("========================================");
        System.out.println("What would you like to do?");
        System.out.println("1. Bat First");
        System.out.println("2. Bowl First");
        dec=br.readLine();
        if(dec.charAt(0)=='1'||dec.equals("1.")||dec.equalsIgnoreCase("Bat first")||dec.equalsIgnoreCase("Batting first")||dec.equalsIgnoreCase("Bat")||dec.equalsIgnoreCase("Batting"))
            return(1);
        else if(dec.charAt(0)=='2'||dec.equals("2.")||dec.equalsIgnoreCase("Bowl first")||dec.equalsIgnoreCase("Bowling first")||dec.equalsIgnoreCase("Bowl")||dec.equalsIgnoreCase("Bowling"))
            return(2);
        else
            return(3);//as a default value
    }//method Won_The_Toss end here
    
    /*In the program from here, 
     * chc=1 or chc2=1 means Player has to Bat and Computer has to Bowl
     * chc=2 or chc2=2 means Player has to Bowl and Computer has to Bat
     */
    int First_Innings(int chc,int over)throws IOException
    {//method First_Innings starts here
        System.out.println("=======================");
        System.out.println("| FIRST INNINGS |");
        System.out.println("=======================");
        System.out.println();
        if(chc==1)//if player has chosen to bat
            System.out.println("YOU ARE BATTING:");
        else if(chc==2)//if player has chosen to bowl
            System.out.println("YOU ARE BOWLING:");
        for(c=0;c<=2;c++)
            System.out.println("===================================="); 
        over=over*6;//stores the limit of number of balls to be played by the one who is batting
        for(ii=1;ii>0;ii++)//gets terminated only by a break statement further in the loop
        {
            System.out.println();
            System.out.print("Enter Your Number: ");
            bb=Integer.parseInt(br.readLine());
            if(bb>6||bb<1)//Again it checks whether player has entered an appropriate number (between 1 and 6)
            {for(ii=1;ii>0;ii++)//if number is an inappropriate number, it continuously runs until the player enters an appropriate number
                {System.out.println("YOU HAVE EITHER TRIED TO CHEAT OR ENTERED A WRONG INPUT..");
                    System.out.println("YOU CANNOT ENTER A NUMBER ABOVE 6 OR BELOW 1.");
                    System.out.println("PLEASE ENTER YOUR NUMBER AGAIN CAREFULLY :-");
                    bb=Integer.parseInt(br.readLine());
                    if(bb>6||bb<1)
                        continue;
                    else
                        break;
                }
            }
            rr=((Math.random())*6);
            rr=rr+1;
            aa=(int)(rr);
            ++ball;//so that ball becomes 1 from 0(its initial value) for the first ball
            System.out.println();
            System.out.println("Computer's Number: "+aa);
            System.out.println();
            System.out.println(ball+" Balls");//Prints the current number of balls played by the one who is batting
            System.out.println("**********");
            System.out.println();
            if(bb==aa)//if both the numbers are the same,
            {
                System.out.println(" ");
                if(chc==1)//if the player is batting, player is declared as Out
                {System.out.println("HOWZATTT!!!!!!");
                    System.out.println(" ");
                    System.out.println("################");
                    System.out.println("################");
                    System.out.println("YOUR FINAL SCORE = "+score1+" runs");
                    System.out.println("################");
                    System.out.println("################");
                    System.out.println(" ");
                    break;//breaks the loop of the First Innings
                }
                else if(chc==2)//if the computer is batting, computer is declared as Out
                {System.out.println();
                    System.out.println("COMPUTER IS OUTT!!!!");
                    System.out.println();
                    System.out.println("################");
                    System.out.println("################");
                    System.out.println("COMPUTER'S FINAL SCORE = "+score1+" runs");
                    System.out.println("################");
                    System.out.println("################");
                    System.out.println();
                    break;//breaks the loop of the First Innings
                }
            }
            else//if the numbers are not same,
            {if(chc==1)//if player is batting,
                {score1=score1+bb;//his score gets added up
                    if(score1>=50&&ff==0)//prints if the player has scored a Half Century
                    {System.out.println("Wow!! You Have Scored A Half-Century!! Keep It Up!!");
                        System.out.println();
                        ff++;//so that ff gets incremented and thus the message never gets printed more than 1 time
                    }
                    if(score1>=100&&cc==0)//prints if the player has scored a Century
                    {System.out.println("Wow!! You Have Scored A Century!!! Keep It Up!!");
                        System.out.println();
                        ff++;
                    }
                }
                else if(chc==2)// if computer is batting
                  score1=score1+aa;//its score gets added up
            }
            //printing the current score after each & every ball;
            if(chc==1)
                System.out.println("Your Current Score Is "+score1+" runs");
            else if(chc==2)
                System.out.println("Computer's Current Score Is "+score1+" runs");
            System.out.println();
            System.out.println("**********");
            if(ball==over)//if player has reached the maximum number of balls
            {System.out.println("YOU'VE PLAYED ENOUGHH BALLS..");
              break;//breaks the First Innings loop
            }
        }
        strt=(score1/ball)*100;//storing the strike rate of the one who was batting
        target=score1+1;//stores the target to score in the second innings
        if(chc==1)//if player was batting first
        {System.out.println("Your Total Score Is "+score1+" runs");
            System.out.println("Your Strike rate : "+strt);
            if(strt>=300)
            {System.out.println("You are a tough competitor!!!");
                System.out.println("You played very well!!!");
            }
            System.out.println("Target score for Computer Is : "+target+" runs");
            System.out.println();
            System.out.println("**********");
        }
        if(chc==2)//if computer was batting first
        {System.out.println("Computer's Total Score Is "+score1+" runs");
            System.out.println("Computer's Strike rate : "+strt);
            if(strt>=300)
            System.out.println("The Computer knows how to play well!!!");
            System.out.println("Target score for Player is "+target+" runs");
            System.out.println();
            System.out.println("**********");
        }
        System.out.println("NOW, ITS TIME FOR THE SECOND INNINGS!!");
        System.out.println("PULL UP YOURSELF FOR THE NEXT HALF OF THE GAME!!");
        for(c=0;c<=2;c++)
            System.out.println("====================================");
        return(score1);//returns the score, scored by the one batting in the first innings, to be printed in the result
    }//method First_Innings ends here

    int Second_Innings(int chc2,int score1,int over)throws IOException
    {//method Second_Innings starts here
        System.out.println("=======================");
        System.out.println("  | SECOND INNINGS |");
        System.out.println("=======================");
        System.out.println();
        if(chc2==1)
            System.out.println("NOW, YOU ARE BATTING:");
        if(chc2==2)
            System.out.println("NOW, YOU ARE BOWLING:");
        for(c=0;c<=2;c++) 
            System.out.println("====================================");
        over=over*6;
        for(ii=1;ii>0;ii++)
        {
            System.out.println();
            System.out.print("Enter Your Number: ");
            bb=Integer.parseInt(br.readLine());
            if(bb>6||bb<1)
            {for(ii=1;ii>0;ii++)
                {System.out.println("YOU HAVE EITHER TRIED TO CHEAT OR ENTERED A WRONG INPUT..");
                    System.out.println("YOU CANNOT ENTER A NUMBER ABOVE 6 OR BELOW 1.");
                    System.out.println("PLEASE ENTER YOUR NUMBER AGAIN CAREFULLY :-");
                    bb=Integer.parseInt(br.readLine());
                    if(bb>6||bb<1)
                        continue;
                    else
                        break;
                }
            }
            rr=((Math.random())*6);
            rr=rr+1;
            aa=(int)(rr);
            ++ball;
            System.out.println();
            System.out.println("Computer's Number: "+aa);
            System.out.println();
            System.out.println(ball+" Balls");
            System.out.println("**********");
            System.out.println();
            if(aa==bb)
            {
                if(chc2==1)
                {System.out.println();
                    System.out.println("HOWZATTT!!!!!!");
                    System.out.println();
                    System.out.println("################");
                    System.out.println("################");
                    System.out.println("YOUR FINAL SCORE = "+score2+" runs");
                    System.out.println("################");
                    System.out.println("################");
                    System.out.println();
                    break;//breaks the loop of Second Innings
                }
                else if(chc2==2)
                {System.out.println();
                    System.out.println("COMPUTER IS OUT!!!!");
                    System.out.println();
                    System.out.println("################");
                    System.out.println("################");
                    System.out.println("COMPUTERS'S FINAL SCORE = "+score2+" runs");
                    System.out.println("################");
                    System.out.println("################");
                    System.out.println();
                    break;//breaks the loop of Second Innings
                }
            }
            else
            {if(chc2==1)
                    score2=score2+bb;//adding up the score of player
                else if(chc2==2)
                    score2=score2+aa;//adding up the score of computer
            }
            strt2=(score2/ball)*100;//calculating the strike rate
            /*score1 means runs scored in the 1st innings;
             *score2 means runs scored in the 2nd innings;
             */
            if(score2>score1)
            {
                if(chc2==1)//if player is batting in the 2nd innings
                {System.out.println(" ");
                    System.out.println("YOU HAVE SCORED MORE THAN THE COMPUTER!!!");
                    System.out.println(" ");
                    System.out.println("################");
                    System.out.println("################");
                    System.out.println("YOUR FINAL SCORE = "+score2+" runs");
                    System.out.println("################");
                    System.out.println("################");
                    System.out.println("Your Strike rate : "+strt2+" runs");
                    if(strt2>300)
                        System.out.println("You played very well!!!");
                    System.out.println(" ");
                    break;
                }
                else if(chc2==2)//if computer is batting in the 2nd innings
                {System.out.println(" ");
                    System.out.println("THE COMPUTER HAS SCORED MORE THAN YOU!!!");
                    System.out.println(" ");
                    System.out.println("################");
                    System.out.println("################");
                    System.out.println("COMPUTER'S FINAL SCORE = "+score2+" runs");
                    System.out.println("################");
                    System.out.println("################");
                    System.out.println("Computer's Strike rate : "+strt2+" runs");
                    if(strt2>=300)
                        System.out.println("The Computer has played really well!!!");
                    System.out.println(" ");
                    break;
                }
            }
            if(ball==over)//if player has reached the maximum number of balls
            {if(chc2==1)
                {System.out.println("You could not score the targeted score within the limited balls");
                    System.out.println("Your Strike rate : "+strt2);
                    if(strt2>300)
                        System.out.println("You played well but not better than the Computer!!!");
                }
                else if(chc2==2)
                {System.out.println("The computer could not score the targeted score within the limited balls");
                    System.out.println("Computer's Strike rate : "+strt2);
                    if(strt2>300)
                        System.out.println("The Computer played really well but lost at last!!!");
                }
                break;
            }
            //printing the current score of the one who is batting after each & every ball;
            if(chc2==1)
                System.out.println("Your Current Score Is "+score2+" runs");
            else if(chc2==2)
                System.out.println("Computer's Current Score Is "+score2+" runs");
            System.out.println();
            System.out.println("**********");
        }
        return(score2);//returns the score, scored by the one batting in the second innings, to be printed in the result
    }//method Second_Innings ends here

    void RESULT(int chc3,int score1,int score2,String name)throws IOException //chc3 stores the code, meaning who batted in the 1st innings;
    {//method RESULT starts here
        for(c=0;c<=2;c++) 
        System.out.println("====================================");
        System.out.println(" ");
        System.out.println("################");
        System.out.println("################");
        if(chc3==1)
        {System.out.println("YOUR FINAL SCORE = "+score1+" runs");
            System.out.println("COMPUTER'S FINAL SCORE = "+score2+" runs");
        }
        else if(chc3==2)
        {System.out.println("COMPUTER'S FINAL SCORE = "+score1+" runs");
            System.out.println("YOUR FINAL SCORE = "+score2+" runs");
        }
        System.out.println("################");
        System.out.println("################");
        System.out.println(" ");
        if((chc3==1&&score1>score2)||(chc3==2&&score1<score2))
            System.out.println("Congratulations "+name+"!! You Have Defeated The Almighty, Computer!!");
        else if((chc3==1&&score1<score2)||(chc3==2&&score1>score2))
            System.out.println("Sorry "+name+", But The Computer Has Defeated You..!");
        else
            System.out.println("It's a Tie..! :(");

        for(c=0;c<=2;c++)
            System.out.println("====================================");
    }//method RESULT ends here

    public static void main(String[]args)throws IOException
    {//main method starts here
        InputStreamReader isr=new InputStreamReader(System.in);
        BufferedReader br=new BufferedReader(isr);
        int infinity=0; // used to keep the game running until the player decides to end the game;
        while(infinity<1)
        {
            int num; // to receive the message whether player has chosen odd or even for doing toss;
            int tr; // to receive the message whether player has won the toss or not;
            int choice; // to receive the message whether player has chosen to bat or bowl first;
            int r; // to store a random number according to which the computer choses whether to bat or bowl first if player has lost the toss;
            int newgame; // used to decide whether the game needs to be ended or restarted;
            int score1;//stores the runs scored in the 1st innings sent by First Innings method
            int score2;//stores the runs scored in the 2nd innings sent by Second Innings method
            int over;//stores the number of overs the player wants to play sent by Over method
            String name;//stores the name of the player sent by Welcome_Player method;
            
            //Making objects of class hc to call the various methods;
            hc obj1=new hc();
            hc obj2=new hc();
            hc obj3=new hc();
            hc obj4=new hc();
            hc obj5=new hc();
            hc obj6=new hc();
            hc obj7=new hc();
            hc obj8=new hc();
            hc obj9=new hc();
            name=obj1.Welcome_Player();//calling the method Welcome_Player and receiving name of player in "name";
            obj2.Instructions();//calling the method Intructions;
            over=obj9.Over();//calling the method Over and receiving no. of overs in "over"
            num=obj3.Odd_or_Even();//calling the method Odd_or_Even and receiving the player's decision;
            tr=obj4.Toss(num);//calling the method Toss, sending the player's decision and receiving Player's Victory or Defeat in the Toss
            if(tr==1)//1 means player has won the toss;
            {choice=obj5.Won_The_Toss();//calling the method Won_The_Toss and receiving player's choice of batting/bowling
                if(choice==1)//if player wants to bat first
                {score1=obj6.First_Innings(1,over);//calling the method First_Innings, sending 1 (means player wants to bat first) and the no. of overs, and receiving the runs scored by the player
                 score2=obj7.Second_Innings(2,score1,over);//calling the method Second_Innings, sending 2 (means player has to bowl next) and the no. of overs, and receiving the runs scored by the computer
                 obj8.RESULT(1,score1,score2,name);//calling the method RESULT to display the Result of the whole match;
                }
                else if(choice==2)
                {score1=obj6.First_Innings(2,over);
                 score2=obj7.Second_Innings(1,score1,over);
                 obj8.RESULT(2,score1,score2,name);
                }
                else//if a default value (i.e. 3) was received
                {System.out.println("Sorry, You Have Entered A Wrong Input...Check Your Choice And Try Again");
                    break;
                }
            }
            else//if the player has lost the Toss, Computer will randomly choose between batting/bowling;
            {
                System.out.println("Sorry, But You Have Lost The Toss!!");
                System.out.println();
                r=(int)(Math.random()*2);
                r=r+1;
                if(r==1)//if by random, 1 comes, computer will bat first and player will bowl;
                {System.out.println("The Computer Has Chosen To Bat First.");
                 System.out.println();
                 score1=obj6.First_Innings(2,over);
                 score2=obj7.Second_Innings(1,score1,over);
                 obj8.RESULT(2,score1,score2,name);
                }
                else//if by random, 2 comes, computer will bowl first and player will bat;
                {System.out.println("The Computer Has Chosen To Bowl First.");
                 System.out.println();
                 score1=obj6.First_Innings(1,over);
                 score2=obj7.Second_Innings(2,score1,over);
                 obj8.RESULT(1,score1,score2,name);
                }
            }
            System.out.println();
            System.out.println("Enter 1 To Play This Game Again.");
            System.out.println();
            System.out.println("Enter 0 Or Any Other Number To Quit.");
            newgame=Integer.parseInt(br.readLine());
            System.out.println();
            if(newgame==1)//if player wants to play again
                System.out.print('\f');//A form feed to wipe out all text; A new match will be held in the next iteration of th while loop;
            else
            {System.out.print('\f');
                System.out.println("Good Bye!");
                break;//breaks the while loop containng the whole program
            }
        }
    }//main method ends here
}//class ends here